### ISSUE TITLE
feature request: save only on the first visit

### ISSUE THREAD

**Issue by iddq** [msindwan/mycache#20]
save only on the first visit
thank you.

**Comment by msindwan** [comment]
Hi @iddq thank you for your suggestion and sorry for the delay. I will try to incorporate this in the next release of mycache. I will be archiving this repo as I don't have much bandwidth to take feature requests, but please feel free to direct any questions to the support page on the chrome webstore!

**Comment by msindwan** [comment]
This was added to release 2.1.0
